      SUBROUTINE CONFR (W, IW, LW)                                          MAIN
 
C* REVISED 6-AUG-91.
C* CALLS MAIN SUBROUTINES.
 
C  AUTHORS - M.J. DALLWITZ AND T.A. PAINE,
C    CSIRO DIVISION OF ENTOMOLOGY,
C    G.P.O. BOX 1700, CANBERRA A.C.T. 2601, AUSTRALIA.
C
C  NOTES.
C
C  THE ROUTINES ARE ORGANIZED INTO GROUPS TO FACILITATE EDITING AND
C    OTHER MANIPULATION. THE GROUP TO WHICH A ROUTINE BELONGS IS
C    INDICATED BY A CODE IN COLUMNS 77-80 OF ITS FIRST LINE.
C  GROUPS STARTING WITH X ARE FOR PARTICULAR MACHINES AND GROUPS
C    STARTING WITH W ARE FOR PARTICULAR TYPESETTING SYSTEMS AND INTERNAL
C    CHARACTER CODES. ONLY ONE GROUP FROM EACH OF THESE CATEGORIES
C    SHOULD BE INCLUDED IN ANY GIVEN IMPLEMENTATION.
C  LINES REQUIRING SPECIAL ATTENTION WHEN THE PROGRAM IS ALTERED OR
C    IMPLEMENTED ON ANOTHER MACHINE ARE MARKED * (FOR CODE) OR /
C    (FOR COMMENTS) IN COLUMN 80. ON THESE CARDS, THE CONTENTS OF
C    OF COLUMNS 73-79 INDICATE THE ACTION REQUIRED:
C    =  MAY NEED ATTENTION IF PROGRAM IS ALTERED.
C
C  THE PROGRAM STORES SYMBOLS ONE PER INTEGER VARIABLE.
C
C--VARIABLES.
C
C    VARIABLES DESCRIBED AS 'WHETHER X' TAKE THE VALUE 1 IF X IS TRUE
C    AND 0 IF X IS FALSE.
C
C  SINGLE-CHARACTER NAMES (EXCEPT W) = TEMPORARY VARIABLES.
C
C  FNAME(I) = NAME OF FILE OPENED ON LOGICAL UNIT I. (LUFXXX)
C  I1 = FIRST POSITION.
C  IA = AN ARRAY.
C  IAC = LOCATION IN ICSTR OF THE FEATURE DESCRIPTION.
C  IADDC(I) = WHETHER CHARACTER I IS TO BE ADDED TO MASK.
C  IADDR = STARTING LOCATION OF ARRAY IN W OR IW. (ALLOC2)
C  IADDT(I) = RECORD ADDRESS OF ADDITIONAL CHARACTERS TO BE INCLUDED
C   FOR TAXON I.
C  IASCND = WHETHER VALUES MUST BE IN ASCENDING ORDER. (DERNGS)
C  IAS = LOCATIONS IN ICSTR OF THE STATE DESCRIPTIONS.
C  IB = POSITION OF BEGINNING OF SOMETHING.
C  IBF = A BUFFER.
C  IBIT = BIT POSITION.
C  IBUF = INPUT BUFFER FOR INPUT RECORD. MUST BE DIMENSION LIBUF.
C    (INQXXX)
C  IC = CHARACTER NUMBER (OLD).
C  ICAP = WHETHER NEXT LETTER OUTPUT IS TO BE CAPITAL. (JSTXXX, CAP)
C  ICARD = FLAG DESCRIBING INPUT CARD IMAGE. -1 IF * (KDSTAR) IS FIRST
C    NON-BLANK SYMBOL, ELSE POSITION OF LAST NON-BLANK SYMBOL.
C  ICDEP = CHARACTER DEPENDENCIES.
C  ICDES = STARTING POSITIONS OF CHARACTER DESCRIPTIONS (IN WORDS FOR
C    MEMORY STORAGE, OR RECORDS FOR DISC STORAGE).
C  ICDIAG = SET OF DIAGNOSTIC CHARACTERS.
C  ICFLAG(IC) = STATUS OF VALUE FOR CHARACTER IC.
C  ICHAR = FLAG GIVING RESULT OF READING CHARACTER DESCRIPTION; OR
C    WHETHER OUTPUTTING CHARACTER.
C  ICHHD = CHARACTER HEADINGS.
C  ICHNSE = WHETHER TO USE CHINESE FORMAT FOR OUTPUT. (MISXXX)
C  ICHSEQ = WHETHER SEQUENCE NUMBERS ARE TO BE INCLUDED IN THE
C    CHARACTERS FILE WHEN CONVERTING TO DELTA FORMAT. (MISXXX)
C  ICKYIMG = RECORD POINTER FOR CHARACTER KEYWORD IMAGES. (MISXXX)
C  ICMAND = WHETHER MANDATORY CHARACTERS SPECIFIED. (MISXXX)
C  ICMD = WHETHER EXPECTING TYPESETTING COMMAND. (IGNXXX)
C  ICMPRS = WHETHER DATA COMPRESSION IS TO BE APPLIED WHEN
C   TRANSLATING INTO DELTA FORMAT. (MISXXX)
C  ICODE = KEY-WORD NUMBER.
C  ICODED = WHETHER CHARACTER IS CODED FOR AN ITEM.
C  ICODES = LIST OF CODE WORDS. (CICOD)
C  ICOFILE = CHARACTER FOR OUTPUT FILE. (MISXXX)
C  ICOL = COLUMN NUMBER.
C  ICOMM = WHETHER COMMENTS ARE TO BE INCLUDED.
C  ICON = CONTROL PHRASES.
C  ICPH = CONTROL-PHRASE NUMBER.
C  ICPTW(IC) = WORD POINTER FOR START OF ATTRIBUTE I. (DISTI)
C  ICPTB(IC) = BIT OFFSET FOR START OF ATTRIBUTE I. (DISTI)
C  ICR = CHARACTER NUMBER READ. (RDCHAR)
C  ICSTR = STORAGE SPACE FOR CHARACTER DESCRIPTIONS (IF ISTYPE.EQ.1),
C    OR BUFFER FOR CHARACTER DESCRIPTIONS (IF ISTYPE.NE.1).
C  ICSYN = STORAGE SPACE FOR CHARACTERS FOR SYNONOMY.
C  ICTIMGE = CHARACTER FOR TAXON IMAGES. (MISXXX)
C  ICTNAME = CHARACTER FOR TAXON NAME. (MISXXX)
C  IDAM = BUFFER FOR HOLDING A MASTER-ITEM DESCRIPTION OR OTHER
C    INFORMATION.
C  IDAT = DATA BUFFER FOR HOLDING A CHARACTER DESCRIPTION,
C    ITEM DESCRIPTION, OR OTHER INFORMATION.
C  IDAV = BUFFER FOR HOLDING A VARIANT-ITEM DESCRIPTION.
C  IDEF = DEFAULT VALUE.
C  IDEPC = WHETHER CHARACTER DEPENDENCIES ARE IN EFFECT. (MISXXX)
C  IDERR = DIRECTIVE ERROR FLAG. (INPXXX)
C  IDIFF = WHETHER VARIANT ITEM IS TO BE COPIED UNCHANGED. (MERGI)
C  IDIM = DIMENSION OF ARRAY. (ALLOC2)
C  IDSENT = FUNCTION SUBR. TESTING TWO SENTENCES FOR IDENTITY.
C  IE = POSITION OF END OF SOMETHING, OR FLAG INDICATING HOW WORD IS TO
C    BE TERMINATED.
C  IEMPC(I) = WHETHER CHARACTER I IS TO BE EMPHASIZED.
C  IEMPF = FEATURE-EMPHASIS FLAGS. IF N TO M IS A RANGE OF
C   FEATURES TO BE EMPHASIZED, THEN IEMPF(IC)=N FOR ALL IC IN THE RANGE.
C  IEMPT(I) = RECORD ADDRESS OF CHARACTERS TO BE EMPHASIZED
C   FOR TAXON I.
C  IENDRC = WHETHER TO ADD RECORD TERMINATOR TO BINARY OUTPUT BUFFER. (BINXXX)
C  IENDWD(I) = POSITION OF END OF LAST COMPLETED WORD IN OUTPUT
C    BUFFER TYPE I. (-1 - BUFFER EMPTY AND INDENTATION HAS NOT TAKEN
C    PLACE. 0 - INDENTATION HAS TAKEN PLACE, BUT THERE IS NO
C    COMPLETED WORD IN THE BUFFER.) (JSTXXX)
C  IERR = ERROR FLAG. 0 - NO ERROR. POSITIVE - ERROR (MAY INDICATE
C    POSITION OF INVALID SYMBOL).
C  IERRAB = WHETHER 'ABSOLUTE ERROR' SET. (MISXXX)
C  IERRPC = WHETHER 'PERCENT ERROR' SET. (MISXXX)
C  IFATT = WHETHER TO OUTPUT FIRST OR LAST VALUE OF A CODED ATTRIBUTE,
C    1=FIRST, 0=LAST. (PAUPTI)
C  IFBEGIN = WHETHER THE APPRORIATE TYPSETTING MARK (FROM MARKTPS) HAS BEEN
C    OUTPUT AT THE START OF THE CURRENT PRINT FILE. (TPSXXX)
C  IFEND = WHETHER THE APPRORIATE TYPSETTING MARK (FROM MARKTPS) HAS BEEN
C    OUTPUT AT THE END OF THE CURRENT PRINT FILE. (TPSXXX)
C  IFETO = LAST FEATURE OUTPUT. (NATTI, WFEAT)
C  IFILS(IT) = WHETHER THERE IS TO BE A NEW FILE AT ITEM IT.
C  IFIRST = WHETHER FIRST LINE. (HEAD)
C  IGNOR = FUNCTION SUBR. TO DETERMINE WHETHER SYMBOL IS PART OF
C    TYPESETTING CODE.
C  IGTYPE = SYMBOL TYPES TO DETERMINE WHETHER SYMBOLS ARE TO BE IGNORED.
C  IHEAD = BUFFER FOR HEADING. (HEDXXX)
C  IHTML = WHETHER TO USE HTML OUTPUT FORMAT. (MISXXX)
C  IIADDC = STARTING LOCATION IN IW OF IADDC. (ADRXXX)
C  IIADDT = STARTING LOCATION IN IW OF IADDT. (ADRXXX)
C  IICDEP = STARTING LOCATION IN IW OF ICDEP. (ADRXXX)
C  IICDES = STARTING LOCATION IN IW OF ICDES. (ADRXXX)
C  IICDIA = STARTING LOCATION IN IW OF ICDIAG. (ADRXXX)
C  IICDNAM = STARTING LOCATION IN IW OF ICDNAM. (ADRXXX)
C  IICHHD = STARTING LOCATION IN IW OF ICHHD. (ADRXXX)
C  IICPTB = STARTING LOCATION IN IW OF ICPTB. (ADRXXX)
C  IICPTW = STARTING LOCATION IN IW OF ICPTW. (ADRXXX)
C  IICSTR = STARTING LOCATION IN IW OF ICSTR. (ADRXXX)
C  IICSYN = STARTING LOCATION IN IW OF ICSYN. (ADRXXX)
C  IIDAM = STARTING LOCATION IN IW OF IDAM. (ADRXXX)
C  IIDAT = STARTING LOCATION IN IW OF IDAT. (ADRXXX)
C  IIDAV = STARTING LOCATION IN IW OF IDAV. (ADRXXX)
C  IIEMPC = STARTING LOCATION IN IW OF IEMPC. (ADRXXX)
C  IIEMPF = STARTING LOCATION IN IW OF IEMPF. (ADRXXX)
C  IIEMPT = STARTING LOCATION IN IW OF IEMPT. (ADRXXX)
C  IIFILS = STARTING LOCATION IN IW OF IFILS. (ADRXXX)
C  IIMC = STARTING LOCATION IN IW OF IMC. (ADRXXX)
C  IIMI = STARTING LOCATION IN IW OF IMI. (ADRXXX)
C  IIMPFL = STARTING LOCATION IN IW OF IMPFLG. (ADRXXX)
C  IIMPL1 = STARTING LOCATION IN IW OF IMPL1. (ADRXXX)
C  IIMPL2 = STARTING LOCATION IN IW OF IMPL2. (ADRXXX)
C  IIOMOR = STARTING LOCATION IN IW OF IOMORC. (ADRXXX)
C  IIPARA = STARTING LOCATION IN IW OF IPARA. (ADRXXX)
C  IIREPS = STARTING LOCATION IN IW OF IREPS. (ADRXXX)
C  IISBND = STARTING LOCATION IN IW OF ISBND. (ADRXXX)
C  IISUMM = STARTING LOCATION IN IW OF ISUMM. (ADRXXX)
C  IITIMG = STARTING LOCATION IN IW OF ITXIMG. (ADRXXX)
C  IITMAD = STARTING LOCATION IN IW OF ITMADD. (ADRXXX)
C  IITPTR = STARTING LOCATION IN IW OF ITPTR. (ADRXXX)
C  IITSHD = STARTING LOCATION IN IW OF ITSHD. (ADRXXX)
C  IITYMK = STARTING LOCATION IN IW OF ITYMK. (ADRXXX)
C  IITYPC = STARTING LOCATION IN IW OF ITYPC. (ADRXXX)
C  IIUFLG = STARTING LOCATION IN IW OF IUFLG. (ADRXXX)
C  IIVFLG = STARTING LOCATION IN IW OF IVFLG. (ADRXXX)
C  IIVCON = STARTING LOCATION IN IW OF IVCON. (ADRXXX)
C  IKSTAT = STARTING LOCATION IN IW OF KSTAT. (ADRXXX)
C  ILAST = ONE MORE THAN LAST ADDRESS ALLOCATED IN W. (ADRXXX)
C  ILCDES = STARTING LOCATION IN IW OF LCDES. (ADRXXX)
C  ILEGAL = 0 IF STRING IS VALID, ELSE POSITION OF ILLEGAL SYMBOL.
C  ILINKC = STARTING LOCATION IN IW OF LINKC. (ADRXXX)
C  ILISTC = WHETHER CHARACTER LIST IS TO BE LISTED. (LISXXX)
C  ILISTD = WHETHER INPUT DATA IS TO BE LISTED. (LISXXX)
C  ILISTI = WHETHER ITEM DESCRIPTIONS ARE TO BE LISTED. (LISXXX)
C  ILISTP = VALUE OF ILISTD AT START OF CHARACTER LIST OR ITEM
C    DESCRIPTIONS. (LISXXX)
C  ILNAME = STARTING LOCATION IN IW OF LNAME. (ADRXXX)
C  ILSTDE = STARTING LOCATION IN IW OF LSTDEP. (ADRXXX)
C  ILUNU = WHETHER ILLUNU HAS BEEN CALLED. ILLUNU MAY BE CALLED FROM
C    WRTREC, WHICH MAY BE CALLED FROM BLKLIN. WHEN ILUNU IS SET,
C    SUBSEQUENT, POTENTIALLY RECURSIVE CALLS TO BLKLIN AND WRTREC,
C    FROM IPRT AND ARROW, ARE PREVENTED. (UNUXXX)
C  IKEYCH = WHETHER A KEY CHARACTER LIST IS BEING USED. (MISXXX)
C  IM = POSITION IN MASK.
C  IMANDC = STARTING LOCATION IN IW OF MANDC. (ADRXXX)
C  IMAX = MAXIMUM ALLOWED VALUE.
C  IMC = CHARACTER MASK. 0 - MASKED OUT. NON-ZERO - MASKED IN.
C  IMGDIR = IMAGE DIRECTORY. (DIRYXX)
C  IMI = ITEM MASK. 0 - MASKED OUT. NON-ZER O - MASKED IN.
C  IMIN = MINIMUM ALLOWED VALUE.
C  IMPFLG = FLAGS INDICATING WHERE IMPLICIT VALUES HAVE BEEN SET IN AN
C    ITEM.
C  IMPL1 = TYPE-1 IMPLICIT VALUES, APPLIED WHEN THE CHARACTER IS
C    COMPLETELY MISSING.
C  IMPL2 = TYPE-2 IMPLICIT VALUES, APPLIED WHEN ON THE CHARACTER NUMBER
C    IS PRESENT.
C  IMPVAL = WHETHER MISSING VALUES ARE TO IMPLY VALUES. (MISXXX)
C  IN = ARRAY INDEX.
C  INAFLG = STARTING LOCATION IN IW OF NAFLG. (ADRXXX)
C  INAME = FLAG GIVING RESULT OF READING ITEM DESCRIPTION.
C  INCL = NUMBER OF ELEMENTS WITH NON-ZERO VALUES. (RDMSK)
C  IND = INDENTATION.
C  INDEC = STARTING LOCATION IN IW OF NDEC. (ADRXXX)
C  INDEN(I) = NORMAL INDENTATION FOR TYPE I OUTPUT. (JSTXXX)
C  INEWFL = STARTING LOCATION IN IW OF NEWFL. (ADRXXX)
C  INEWOR = STARTING LOCATION IN IW OF NEWOR. (ADRXXX)
C  INORNG = STARTING LOCATION IN IW OF NORNG. (ADRXXX)
C  INSBLK = WHETHER TO INSERT A BLANK CHARACTER BETWEEN BUFFERS IN BINARY
C    OUTPUT. (BINXXX)
C  INSIMGFN = WHETHER TO INSERT THE IMAGE FILE NAME IN THE IMAGE LINK IN THE
C    "CHARACTER FOR TAXON IMAGES" IN HTML OUTPUT.
C  INSRVA = WHETHER TO INSERT REDUNDANT VARIANT ATTRIBUTES.
C    0 - DO NOT INSERT. 1 -INSERT. -1 - OMIT EXISTING ATTRIBUTES
C    FROM DATA. (MISXXX)
C  INSTAT = STARTING LOCATION IN IW OF NSTAT. (ADRXXX)
C  IOA = STAGE REACHED IN OUTPUT OF ATTRIBUTE. 0 - NOTHING OUTPUT.
C    1 - OUTPUT UP TO FEATURE COMMENT. 2 - OUTPUT UP TO STATE VALUE.
C    3 - OUTPUT UP TO STATE COMMENT. (NATTI)
C  IOFONT = WHETHER THERE ARE OVERLAY FONTS. (FNTXXX)
C  IOMCAP = WHETHER TO CAPITALIZE. IF 1, THE CAPITALIZATION ESCAPE
C    CHARACTER, KCAPMK, IS OMITTED FROM OUTPUT AND THE FOLLOWING LETTER
C    IS NOT CAPITALIZED. IF 0, NO ACTION IS TAKEN. (CAPXXX)
C  IOMCMT = WHETHER TO OMIT COMMENTS. (MISXXX)
C  IOMLOW = WHETHER TO 'OMIT LOWER FOR CHARACTERS'. (MISXXX)
C  IOMNSC = WHETHER TO OMIT INNER (NESTED) COMMENTS. (MISXXX)
C  IOMORC = WHERE TO OMIT "OR" IN CHARACTER DESCRIPTIONS.
C  IOMSTC = WHETHER TO OMIT STATE CODES WHEN OUTPUTTING DELTA FORMAT.
C  IOMTOR = WHETHER TO OMIT "OR" FROM CHARACTER DESCRIPTIONS. (MISXXX)
C   (MISXXX)
C  IOMUSP = WHETHER TO OMIT SPACES BEFORE UNITS. (MISXXX)
C  IOUNC = WHETHER TO OUTPUT UNCODED VALUES IN DELTA FORMAT. (MISXXX)
C  IOUT = OUTPUT BUFFERS. (JSTXXX)
C  IPACH = WHETHER ALL CHARACTERS (INCLUDING MASKED OUT) ARE TO BE
C    PRINTED FOR 'PRINT CHARACTER DESCRIPTIONS' AND 'PRINT ITEM
C    DESCRIPTIONS'. SET BY 'PRINT ALL CHARACTERS' DIRECTIVE. (MISXXX)
C  IPARA(IC) = WHETHER THERE IS TO BE A NEW PARAGRAPH AT CHARACTER IC.
C  IPCHAR = WHETHER CHARACTER DESCRIPTIONS ARE TO BE PRINTED. (TRNXXX)
C  IPCHN = WHETHER CHARACTER NUMBERS ARE TO BE PRINTED IN
C    NATURAL-LANGUAGE DESCRIPTIONS. (MISXXX)
C  IPITEM = WHETHER ITEM DESCRIPTIONS ARE TO BE PRINTED. (TRNXXX)
C  IPOINT = POSITION AT WHICH POINTER IS TO BE PRINTED.
C  IPNAME = WHETHER TAXON NAMES ARE TO BE PRINTED. (TRNXXX)
C  IPOLD = WHETHER OLD CHARACTER OR ITEM NUMBER IS TO BE PRINTED.
C  IPS = TYPE OF PSEUDO-VALUE (ITS-ITSS).
C    1 - VARIABLE. 2 - UNKNOWN. 3 - INAPPLICABLE.
C  IPSUMM = WHETHER SUMMARY STATISTICS ARE TO PRINTED.
C  IPUNC = WHETHER LIST OF UNCODED CHARACTERS IS TO BE OMITTED FROM
C    NATURAL LANGUAGE DESCRIPTIONS. (MISXXX)
C  IR = RESULT OF TEST FOR CONTROL PHRASE.
C  IRAB = WHETHER ANGLE BRACKETS ARE TO BE REPLACED BY PARENTHESES
C    IN NATURAL LANGUAGE DESCRIPTIONS. (MISXXX)
C  IRECDA = RECORD POSITION IN DIRECT ACCESS FILE.
C  IREGHD = REGISTRATION HEADING (REGXXX)
C  IREGSHD = REGISTRATION SUBHEADING (REGXXX)
C  IREGVD = REGISTRATION VALIDATION STRING (REGXXX)
C  IREPS = CHARACTER GROUPS WHERE SEMICOLON IS TO BE REPLACED BY COMMA.
C  IRSEMI = WHETHER TO REPLACE SEMICOLONS BY COMMAS. (MISXXX)
C  IRTF = WHETHER TO USE RTF OUTPUT FORMAT. (MISXXX)
C  IS = STATE NUMBER OR POSITION OF STATE DESCRIPTION.
C  ISBND = STATE BOUNDARIES FOR KEY CHARACTERS.
C  ISCALC = WHETHER CHARACTERS HAVE BEEN SCALED. (MISXXX)
C  ISCALF = STARTING LOCATION IN W OF SCALF. (ADRXXX)
C  ISEN, ISEN1, ISEN2 = A SENTENCE.
C  ISENT = WHETHER A VALID SENTENCE WAS READ.
C  ISEQ = WHETHER RECORDS HAVE SEQUENCE NUMBERS. (INQXXX)
C  ISET = FLAG INDICATING TYPE OF VALUES TO BE SET. (RDMSK)
C  ISHOW = BUFFER ASSOCIATED WITH *SHOW DIRECTIVE. (SHOXXX)
C  ISR = STATE NUMBER READ.
C  ISTAR = WHETHER STAR IS FIRST NON-BLANK SYMBOL IN BUFFER.
C  ISTAT(I) = WHETHER STATE I IS PRESENT.
C  ISTYPE = CHARACTER-DESCRIPTION STORAGE FLAG. 1 - STANDARD STORAGE
C    IN MAIN MEMORY. 2 - NON-STANDARD STORAGE. (STOXXX)
C  ISUMM = SUMMARY STATISTICS.
C  ISUPIMG = RECORD POINTER FOR STARTUP IMAGES. (MISXXX)
C  ISV = INDEX OF VALUE IN A SUBGROUP.
C  ISW = STARTING POSITIONS OF WORDS. (JSTWD, JSTTPS)
C  ITIMGE = WHETHER THERE TAXON IMAGES. IF ITIMGE > NC, IMAGES WERE SPECIFIED
C    BY THE `TAXON IMAGES' DIRECTIVE.
C  ITCOD = EXTERNAL CHARACTER-TYPE CODES. SECOND DIMENSION MUST BE
C    AT LEAST NTCOD. (TCHXXX)
C  ITDIAG(I) = RECORD POINTER TO DIAGNOSTIC CHARACTERS FOR ITEM I.
C  ITERM = FLAG INDICATING TYPE OF DELIMITER. 0 - KDSTAR.
C    1 - KDSTAR OR KDNUM.
C  ITIMPL = WHETHER IMPLICIT VALUES ARE TO BE TRANSLATED IN DELTA FORMAT
C    AND NATURAL-LANGUAGE DESCRIPTIONS. (MISXXX)
C  ITINAP = WHETHER INAPPLICABLES ARE TO PRINTED IN NATURAL-LANGUAGE
C    DESCRIPTIONS. (MISXXX)
C  ITKYIMG = RECORD POINTER FOR TAXON KEYWORD IMAGES. (MISXXX)
C  ITM = BUFFER TO HOLD A TRANFORMED ITEM.
C  ITMHDGS = WHETHER `ITEM HEADINGS' DIRECTIVE HAS BEEN USED. (MISXXX)
C  ITMFILS = WHETHER `ITEM OUTPUT FILES' DIRECTIVE HAS BEEN USED. (MISXXX)
C  ITMADD = FLAGS INDICATING WHERE DATA HAS BEEN ADDED TO AN ITEM.
C  ITPTR(I) = RECORD NUMBER AT WHICH ITEM I STARTS IN DIRECT-ACCESS
C    FILE. (DISTI)
C  ITMSEQ = WHETHER SEQUENCE NUMBERS ARE TO BE INCLUDED IN THE ITEMS
C    FILE WHEN CONVERTING TO DELTA FORMAT.
C  ITPSET = WHETHER TYPSETTING MARKS ARE TO BE INCLUDED IN OUTPUT.
C    0 - DO NOT ADD MARKS. 1 - ADD MARKS. -1 - REMOVE EXISTING MARKS
C    FROM DATA. (TPSXXX)
C  ITRAN INDICATES THE TRANSLATION TO BE CARRIED OUT. (TRNXXX)
C    0 - NO TRANSLATION (DEFAULT).  1 - KEY FORMAT.
C    2 - HENNIG FORMAT.             3 - DELTA FORMAT.
C    4 - NATURAL LANGUAGE.          5 - SPARE.
C    6 - SPARE.                     7 - EXIR FORMAT.
C    8 - PAYNE FORMAT.              9 - INTKEY FORMAT.
C   10 - DISTANCE FORMAT.          11 - PAUP FORMAT.
C  ITRUNC = POSITION AT WHICH INPUT BUFFER HAS BEEN TRUNCATED. (RDBUF)
C  ITS = TYPE OF SUBGROUP.
C  ITSF = FLAGS INDICATING WHICH PSEUDOVALUES ARE PRESENT IN AN
C    ATTRIBUTE. ITSF(1) - VARIABLE. ITSF(2) - UNKNOWN.
C    ITSF(3) - INAPPLICABLE.
C  ITSHD = ITEM SUBHEADINGS. ITSHD(IC) POINTS TO THE STARTING LOCATION
C    IN ITSHD OF THE SUBHEADING FOR CHARACTER IC.
C  ITSS = 1 LESS THAN SMALLEST PSEUDOVALUE FLAG (SUBGROUP TYPE).
C    CURRENTLY 5. (ITSXXX)
C  ITUNC = WHETHER UNCODED ATTRIBUTES ARE TO BE TRANSLATED INTO
C    NATURAL LANGUAGE. (MISXXX)
C  ITYMK = TYPESETTING MARKS. (TPSXXX)
C  ITYPC = CHARACTER TYPES.
C    1 - UNORDERED MULTISTATE. 2 - ORDERED MULTISTATE.
C    3 - INTEGER NUMERIC. 4 - REAL NUMERIC. 5 - TEXT.
C    -1 - EXCLUSIVE UNORDERED MULTISTATE.
C    -2 - EXCLUSIVE ORDERED MULTISTATE.
C  IUFLG = BIT ARRAY TO FLAG UNKNOWN CHARACTERS.
C  IULA = WHETHER REPEATED ATTRIBUTES IN AN ITEM ARE TO REPLACE THE
C    EARLIER VERSIONS. (ULAXXX)
C  IUMEAN = WHETHER TO USE MEAN VALUES. (MISXXX)
C  IUNRNG = WHETHER TO USE NORMAL RANGES. (MISXXX)
C  IUNVAR. IF 0 (DEFAULT), DCR-TAXON FORMAT CODES UNKNOWN AND MISSING
C    AS *, IF NON-ZERO, AS VARIABLE (ALL STATES PRESENT). (MISXXX)
C  IUSELNG1 = THE PREFERRED LANGUAGE TO BE EXTRACTED FROM COMMENTS. (LANGXX)
C  IUSELNG2 = THE LANGUAGE TO BE USED IF USELNG1 IS NOT PRESENT IN A COMMENT. (LANGXX)
C  IV = INTEGER STATE VALUE.
C  IVAL(IC) = VALUE FOR CHARACTER IC.
C  IVARIT = 1 IF VARIANT ITEM, 0 IF MAIN ITEM. (INIXXX)
C  IVCON = CONSTRAINTS FOR NUMERIC CHARACTERS. SEE SUBR. RDVCON.
C  IVFLG = BIT ARRAY TO FLAG VARIABLE CHARACTERS.
C  IW = INTEGER STORAGE POOL. (BLANK COMMON)
C  IWRD = POSITION IN BUFFER OF WORD IN WHICH A BIT FIELD STARTS.
C  IWRK = WORKING SPACE OF LENGTH LOUT. (WRKXXX)
C  IWST = FIRST ELEMENT TO BE USED IN W AND IW.
C  IWTC = STARTING LOCATION IN W OF WTC. (ADRXXX)
C  IWTI = STARTING LOCATION IN W OF WTI. (ADRXXX)
C  IWW1C = STARTING LOCATION IN IW OF WW1C. (ADRXXX)
C  IWW2C = STARTING LOCATION IN W OF WW2C. (ADRXXX)
C  IWW1I = STARTING LOCATION IN W OF WW1I. (ADRXXX)
C  IWW2I = STARTING LOCATION IN W OF WW2I. (ADRXXX)
C  IWW1S = STARTING LOCATION IN W OF WW1S. (ADRXXX)
C  IWW2S = STARTING LOCATION IN W OF WW2S. (ADRXXX)
C  JB = STARTING POSITION IN A BUFFER.
C  JBDAT = POSITION OF BEGINNING OF DATA FIELD IN IBUF. (INPXXX)
C  JBUF = CURRENT POSITION IN IBUF. (INPXXX)
C  JC = CHARACTER NUMBER (NEW).
C  JCEX = EXIR CHARACTER (DESCRIPTOR) NUMBER.
C  JCM = MASKED-IN-CHARACTER NUMBER.
C  JCSTR = NUMBER OF ELEMENTS OF CHARACTER-STORAGE MEDIUM IN USE
C    (IN WORDS FOR MEMORY STORAGE, OR RECORDS FOR DISC STORAGE).
C  JDIR = DIRECTIVE-USE FLAGS. (CHKDIR)
C  JDIR1, ... JDIR5 = DIRECTIVE-USE FLAGS FOR TYPE-1...5 DIRECTIVES.
C    (DIR1XX,...DIR5XX)
C  JE = LOCATION IN IBUF IMMEDIATELY AFTER CONTROL WORD OR DATA; OR
C    ENDING POSITION IN A BUFFER.
C  JEDAT = POSITION OF END OF DATA FIELD IN IBUF. (INPXXX)
C  JES = POSITION OF END OF SEQUENCE FIELD. (RDBUF)
C  JF = POSITON IN BUFFER.
C  JG = POSITION OF START OF GROUP.
C  JGI = POSITION OF START OF GROUP IN NEW ITEM.
C  JGN = POSITION IMMEDIATELY AFTER END OF GROUP.
C  JHD = STARTING LOCATION OF NEXT HEADING TO BE PRINTED.
C  JI = NUMBER OF ITEMS (AS CURRENTLY KNOWN). (INIXXX)
C  JIC = ITEM NUMBER IN CREATION RUN OF A BINARY FILE.
C  JIDAT = LAST ELEMENT IN USE IN IDAM OR IDAV.
C  JIM = NUMBER OF MASKED-IN ITEMS (AS CURRENTLY KNOWN). (INIXXX)
C  JIOUT(I) = CURRENT POSITION IN OUTPUT BUFFER TYPE I. (JSTXXX)
C  JIEMPF = WHETHER THE NEXT FEATURE PRINTED IS TO BE EMPHASIZED.
C    (NATTI, WFEAT)
C  JITM = CURRENT POSITION IN ITM.
C  JLIS = LENGTH OF ENCODED LISTING RECORD. (INQXXX)
C  JMAX = MAXIMUM VALUE.
C  JOUT = POSITION IN OUTPUT BUFFER.
C  JPACH = WHETHER ALL CHARACTERS (INCLUDING MASKED OUT) ARE TO BE
C    PRINTED FOR 'PRINT CHARACTER DESCRIPTIONS' AND 'PRINT ITEM
C    DESCRIPTIONS'.
C  JPARA = WHETHER NEW PARAGRAPH IS REQUIRED. (NATTI)
C  JPRE = VALUE TO WHICH ELEMENTS OF MASK, ETC., ARE INITIALIZED.
C    (RDMSK)
C  JRECH = HOW CHARACTERS ARE TO BE RENUMBERED. 0 - NO RENUMBERING.
C    1 - MASKED-IN CHARACTERS NUMBERED CONSECUTIVELY.
C    2 - SPECIAL RENUMBERING. (DELTC,TRANC)
C  JS = LOCATION OF SYMBOL IN SENTENCE; OR NEW STATE NUMBER.
C  JS1, JS2 = LOCATION OF SYMBOL IN SENTENCE.
C  JSEN = A SENTENCE.
C  JSEQ = TEMPORARY COPY OF ISEQ.
C  JSET = VALUE TO WHICH ELEMENT OF MASK, ETC., IS SET. (RDMSK)
C  JSG = POSITION OF START OF SUBGROUP.
C  JSGI = POSITION OF START OF SUBGROUP IN NEW ITEM.
C  JSGN = POSITION OF START OF NEXT SUBGROUP.
C  JT = NUMBER OF TAXA (AS CURRENTLY KNOWN). (INIXXX)
C  JTCOD = INTERNAL CHARACTER-TYPE CODES. DIMENSION AT LEAST NTCOD.
C    (TCHXXX)
C  JTYPC = ABSOLUTE VALUE OF ITYPC(IC).
C  KA, ... KZ = ALPHABETIC SYMBOLS. (ALPXXX)
C  KALPH = ALPHABETIC SYMBOLS.
C  KBLANK = BLANK SYMBOL. (BLKXXX)
C  KCAPMK = ESCAPE SYMBOL USED TO INDICATE NO CAPITALIZATION OF THE FOLLOWING
C    CHARACTER. (CAPXXX)
C  KCOLON = COLON SYMBOL. (SYMXXX)
C  KCOMMA = COMMA (,) SYMBOL. (SYMXXX)
C  KDAMP = AMPERSAND (&) DELIMITER SYMBOL. (DELXXX)
C  KDASH = DASH (-) SYMBOL. (SYMXXX)
C  KDCOLN = COLON (:) DELIMITER SYMBOL. (DELXXX)
C  KDCOM = COMMA (,) DELIMITER SYMBOL. (DELXXX)
C  KDEC = DECIMAL-POINT (.) SYMBOL. (NUMXXX)
C  KDINF = TILDE (~) DELIMITER SYMBOL. (DELXXX)
C  KDLBRA = LEFT ANGLE BRACKET (<) DELIMITER SYMBOL. (DELXXX)
C  KDLPAR = LEFT BRACKET (() DELIMITER SYMBOL. (DELXXX)
C  KDNUM = NUMERO (#) DELIMITER SYMBOL. (DELXXX)
C  KDOLLA = DOLLAR ($) SYMBOL. (SYMXXX)
C  KDPLUS = PLUS (+) DELIMITER SYMBOL (RECORD CONTINUATION). (DELXXX)
C  KDRANG = RANGE (-) DELIMITER SYMBOL. (DELXXX)
C  KDRBRA = RIGHT ANGLE BRACKET (>) DELIMITER SYMBOL. (DELXXX)
C  KDRPAR = RIGHT BRACKET ()) DELIMITER SYMBOL. (DELXXX)
C  KDSOL = SOLIDUS (/) DELIMITER SYMBOL. (DELXXX)
C  KDSTAR = STAR (*) DELIMITER SYMBOL. (DELXXX)
C  KDSTOP = FULL STOP (.) DELIMITER SYMBOL. (DELXXX)
C  KEQUAL = EQUALS (=) SYMBOL. (SYMXXX)
C  KEXCL = EXCLAMATION MARK (!) SYMBOL. (SYMXXX)
C  KFF = FORM FEED. (FFFXXX)
C  KLPAR = LEFT PARENTHESIS (() SYMBOL. (SYMXXX)
C  KMINUS = MINUS (-) SYMBOL. (NUMXXX)
C  KNA = NOT-APPLICABLE-PSEUDOVALUE CODE (-). (VALXXX)
C  KNUM = NUMERAL (0123456789) SYMBOLS. (NUMXXX)
C  KODEXI = KEY WORDS FOR EXIR CONTROL CARDS. (EXICRD)
C  KODKEY = KEY WORDS FOR KEY CONTROL CARDS. (KEYCRD)
C  KODPAY = KEY WORDS FOR PAYNE CONTROL CARDS. (PAYCRD)
C  KODTRA = TRANLATION-OPTION CODES. (DIR4)
C  KPOINT = POINTER (^) SYMBOL. (SYMXXX)
C  KQUEST = QUESTION MARK (?) SYMBOL. (SYMXXX)
C  KRPAR = RIGHT PARENTHESIS ()) SYMBOL. (SYMXXX)
C  KSEMI = SEMICOLON (;) SYMBOL. (SYMXXX)
C  KSOL = SOLIDUS (/) SYMBOL. (SYMXXX)
C  KSTAR = STAR (*) SYMBOL. (SYMXXX)
C  KSTAT = NUMBERS OF KEY STATES.
C  KSTOP = FULL STOP (.) SYMBOL. (SYMXXX)
C  KUNK = UNKNOWN-PSEUDOVALUE CODE (U). (VALXXX)
C  KVAL = CHARACTER-VALUE CODES. (VALXXX)
C  KVAR = VARIABLE-PSEUDOVALUE CODE (V). (VALXXX)
C  KVERT = VERTICAL BAR (! OR ASCII 124) SYMBOL. (SYMXXX)
C  LA = LENGTH OF ARRAY.
C  LBF = LENGTH OF BUFFER.
C  LCDES = LENGTHS OF CHARACTER DESCRIPTIONS.
C  LCDNAM = LENGTH OF THE FILENAME IN THE `CHECK FOR CD' DIRECTIVE. (MISXXX)
C  LCSTR = DIMENSION OF ICSTR. (DIMXXX)
C  LD = TYPE OF DIRECTIVE ABOUT TO BE PROCESSED. (CHKDIR)
C  LDIR = DIRECTIVE-TYPE CURRENTLY BEING PROCESSED (1-5). (DIRXXX)
C  LENDRC = WHETHER LAST RECORD WAS TERMINATED. (BINXXX)
C  LFNAME(I) = LENGTH OF NAME OF FILE OPENED ON LOGICAL UNIT I. (LUFXXX)
C  LHEAD = DIMENSION OF IHEAD. MUST BE AT LEAST 22. (HEDXXX)
C  LIBUF = LENGTH OF INPUT BUFFER. MUST AGREE WITH DIMENSION OF IBUF.
C    (INQXXX)
C  LICDEP = LENGTH OF ICDEP. (MISXXX)
C  LIDAT = DIMENSION OF IDAT, IDAM, IDAV. MAXIMUM DIMENSION OF ISBND.
C    (DIMXXX)
C  LIMGDIR = LENGTH OF IMGDIR. (DIRYXX)
C  LINKC(IC) = NUMBER OF FIRST CHARACTER TO WHICH CHARACTER IC IS
C    TO BE LINKED IN NATURAL-LANGUAGE DESCRIPTIONS. 0 IF NONE.
C  LISIND = INDENTATION OF LISTING TO ALLOW FOR FILENAMES
C    AND RECORD NUMBERS. (INQXXX)
C  LISOUT = ENCODED LISTING RECORD. (INQXXX)
C  LITM = LENGTH OF ITEM.
C  LKVAL = NUMBER OF CHARACTER-VALUE CODES IN USE (NOT INCLUDING
C   THE PSEUDOVALUE CODES). (VALXXX)
C  LLUNI = VALUE OF LUNI WHEN CURRENT BUFFER WAS READ. (INQXXX)
C  LMSK = LENGTH OF MASK, ETC. (RDMSK)
C  LNAME(I) = LENGTH OF TAXON NAME I. (DISTI)
C  LNKC = WHETHER CHARACTERS ARE LINKED IN NATURAL-LANGUAGE
C    DESCRIPTIONS. (MISXXX)
C  LOUT = LENGTH OF EACH OUTPUT BUFFER AND THE WORKING SPACE. MUST
C    AGREE WITH FIRST DIMENSION OF IOUT AND DIMENSION OF IWRK. (JSTXXX)
C  LOUTDIR = LENGTH OF OUTDIR. (DIRYXX)
C  LPAGE = NUMBER OF LINES IN A LINE-PRINTER PAGE. (LUOXXX)
C  LPRDEF = DEFAULT PRINT WIDTH (MINIMUM 40). (LUOXXX)
C  LPRINT = NUMBER OF LINES TO BE PRINTED ON EACH LINE-PRINTER PAGE
C     (INCLUDING LTOP). (LUOXXX)
C  LPUDEF = DEFAULT OUTPUT (PUNCH) WIDTH (MINIMUM 40). (LUOXXX)
C  LRECDA = RECORD LENGTH OF DIRECT-ACCESS OUTPUT FILE. THE LENGTH IS
C    DEFINED AS THE NUMBER OF LONG WORDS (I.E. INTEGER*4) IN THE RECORD.
C    (LUNDAX)
C  LRECSC = LENGTH OF SCRATCH FILES FOR STORING NC CHARACTER NUMBERS. (SCRCXX)
C  LRECSS = LENGTH OF SPECIAL-STORAGE RECORDS. THE LENGTH IS DEFINED AS
C    DEFINED AS THE NUMBER OF LONG WORDS (I.E. INTEGER*4) IN THE RECORD.
C    NOTE. SPECIAL STORAGE IS USUALLY IMPLEMENTED AS A DIRECT-ACCESS
C    UNFORMATTED FILE (NOT TO BE CONFUSED WITH THE DIRECT-ACCESS FILES
C    USED AS THE OUTPUT FILES FOR SOME TRANSLATIONS, E.G. KEY).
C    THIS FILE IS ACCESSED ENTIRELY THROUGH THE ROUTINES STO AND
C    FET, IN THE MACHINE-DEPENDENT MODULES. (STOXXX)
C  LREGHD = LENGTH OF REGISTRATION HEADING BUFFER (REGXXX)
C  LREGSHD = LENGTH OF REGISTRATION SUBHEADING BUFFER (REGXXX)
C  LREGVD = LENGTH OF REGISTRATION VALIDATION STRING BUFFER (REGXXX)
C  LS = LENGTH OF A TEXT STRING.
C  LSEN = LENGTH OF SENTENCE.
C  LSG = LENGTH OF SUBGROUP.
C  LSGI = LENGTH OF SUBGROUP IN NEW ITEM.
C  LSHOW = DIMENSION OF ISHOW. (SHOXXX)
C  LSTDEP = CHARACTERS WHICH HAVE HAD DEPENDENCY DATA ADDED.
C  LTAXON(I) = LENGTH OF NAME OF TAXON I. (DISTI)
C  LTNAME = LENGTH OF TNAME IN TNAMEX. (TNAMEX)
C  LTOP = NUMBER OF LINES TO BE SKIPPED AT TOP OF PAGE. (LUOXXX)
C  LU(I) = I-TH LOGICAL UNIT IN LUNXXX. LU(1) IS EQUIVALENCED TO LUNE.
C  LUN = LOGICAL UNIT.
C  LUNBI = LOGICAL UNIT FOR BINARY INPUT. (LUNXXX)
C  LUNBO = LOGICAL UNIT FOR BINARY OUTPUT. (LUNXXX)
C  LUNCOM(J) = COMPATIBILITY OF LOGICAL-UNIT-TYPE J. (LUOXXX)
C    LUNCOM = 2, 2, 2, 4, 5, 6, 7, 8, 9, 10, 11 IF ITPSET.LE.0.
C    LUNCOM = 2, 2, 4, 4, 5, 6, 7, 8, 9, 10, 11 IF ITPSET.GT.0.
C  LUND = LOGICAL UNIT FOR DIRECTIVES INPUT. (LUNDXX)
C  LUNDA =  LOGICAL UNIT FOR DIRECT-ACCESS OUTPUT. (LUNXXX)
C  LUNE = LOGICAL UNIT FOR ERROR MESSAGES. (LUNXXX)
C  LUNI = LOGICAL UNIT FOR ORDINARY (CARD-TYPE) INPUT. (LUNXXX)
C  LUNL = LOGICAL UNIT FOR LISTING INPUT DATA. (LUNXXX)
C  LUNO = LOGICAL UNIT FOR PRINTER OUTPUT, EXCEPT INPUT LISTING
C    AND ERROR MESSAGES. (LUNXXX)
C  LUNP = LOGICAL UNIT FOR NON-PRINTER OUTPUT. (LUNXXX)
C  LUNPAG(I) = WHETHER LOGICAL UNIT I IS PAGED. (LUOXXX)
C  LUNPRE(J) = PREVIOUS VALUE OF LOGICAL UNIT TYPE J. (LUOXXX)
C  LUNREC(I) = CURRENT RECORD NUMBER ON LOGICAL UNIT I. (LUOXXX)
C  LUNS1 = FIRST SCRATCH LOGICAL UNIT (SEQUENTIAL). (LUNXXX)
C  LUNS2 = SECOND SCRATCH LOGICAL UNIT (SEQUENTIAL). (LUNXXX)
C  LUNS3 = THIRD SCRATCH LOGICAL UNIT (DIRECT-ACCESS, CHARACTER LIST
C    SPECIAL STORAGE). (LUNXXX)
C  LUNS4 = FOURTH SCRATCH LOGICAL UNIT (DIRECT-ACCESS). (LUNXXX)
C  LUNS5 = FIFTH SCRATCH LOGICAL UNIT (DIRECT-ACCESS). (LUNXXX)
C  LUNS6 = SIXTH SCRATCH LOGICAL UNIT (DIRECT-ACCESS). (LUNXXX)
C  LUNTI = LOGICAL UNIT FOR TERMINAL INPUT. (LUTXXX)
C  LUNTO = LOGICAL UNIT FOR TERMINAL OUTPUT. (LUTXXX)
C  LUNTS1 = UNIT TYPE FOR FIRST SCRATCH UNIT. (SCRXXX)
C  LUNTS2 = UNIT TYPE FOR SECOND SCRATCH UNIT. (SCRXXX)
C  LUNTS3 = UNIT TYPE FOR THIRD SCRATCH UNIT. (SCRXXX)
C  LUNTS4 = UNIT TYPE FOR FOURTH SCRATCH UNIT. (SCRXXX)
C  LUNTS5 = UNIT TYPE FOR FIFTH SCRATCH UNIT. (SCRXXX)
C  LUNTS6 = UNIT TYPE FOR SIXTH SCRATCH UNIT. (SCRXXX)
C  LUNTS7 = UNIT TYPE FOR SEVENTH SCRATCH UNIT. (SCRXXX)
C  LUNTYP = TYPE OF LOGICAL UNIT.
C    1 - ERRORS. 2 - LISTING. 3 - PRINTER. 4 - OUTPUT(PUNCH).
C    5 - FIRST SCRATCH. 6 - BINARY OUTPUT. 7 - BINARY INPUT.
C    8 - CARD INPUT. 9 - DIRECT ACCESS. 10 - SECOND SCRATCH.
C    11 - THIRD SCRATCH (FOR CHARACTER SPECIAL STORAGE).
C    12 - FOURTH SCRATCH (DIRECT ACCESS).
C    13 - FIFTH SCRATCH (DIRECT ACCESS).
C    14 - SIXTH SCRATCH (DIRECT ACCESS).
C    15 - SEVENTH SCRATCH (DIRECT ACCESS).
C  LUNUSE(I) = COMPATIBILITY OF LOGICAL UNIT I (SEE LUNCOM).
C    -1 IF UNIT HAS NOT BEEN USED. (LUOXXX)
C  LVWD(I) = LENGTH OF I-TH WORD STORED IN VWORD. (VLWXXX)
C  LW = DIMENSION OF W (I.E. LENGTH OF BLANK COMMON).
C    NOTE: INTEGERS AND REALS MUST OCCUPY THE SAME AMOUNT OF MEMORY.
C  LWIDTH(I) = LINE WIDTH FOR OUTPUT TYPE I. (JSTXXX)
C  MANDC = WHETHER CHARACTERS ARE MANDATORY.
C  MASTIN = 1 IF MASTER ITEM MASKED IN, 0 OTHERWISE. (INIXXX)
C  MAXWSK = MAXIMUM NUMBER OF WORDS TO BE SKIPPED. (SKDELW)
C  MAXVWD = MAXIMUM LENGTH OF A WORD IN THE VOCABULARY. (VLWXXX)
C  MBY = THE WORD 'BY'. (EXICHA)
C  MCODE = THE WORD 'CODE'. (EXICHA)
C  MI = MAXIMUM NUMBER OF ITEMS. (DIMXXX)
C  MINN = THE WORD 'IN'. (EXICHA)
C  MIREC = MAXIMUM LENGTH OF INPUT RECORDS. (INQXXX)
C  MISTOP = NUMBER OF ITEMS TO BE READ AND PROCESSED. DEFINED BY THE
C    'STOP AFTER ITEM' DIRECTIVE. (INIXXX)
C  MM1C = INTEGER WORKING SPACE OF LENGTH NC. USES SAME STORAGE AS WW1C.
C  MM2C = INTEGER WORKING SPACE OF LENGTH NC. USES SAME STORAGE AS WW2C.
C  MM1I = INTEGER WORKING SPACE OF LENGTH MI. USES SAME STORAGE AS WW1I.
C  MM2I = INTEGER WORKING SPACE OF LENGTH MI. USES SAME STORAGE AS WW2I.
C  MM1S = INTEGER WORKING SPACE OF LENGTH MS. USES SAME STORAGE AS WW1S.
C  MM2S = INTEGER WORKING SPACE OF LENGTH MS. USES SAME STORAGE AS WW2S.
C  MNAME = THE WORD 'NAME'. (EXICHA)
C  MORD = THE WORDS 'ORDER FROM'. (EXICHA)
C  MS = MAXIMUM NUMBER OF STATES. (DIMXXX)
C  MTFILE = NUMBER OF ITEM OUTPUT FILES SPECIFIED BY TAXON NAME. (MISXXX)
C  MTHEAD = NUMBER OF ITEM HEADINGS SPECIFIED BY TAXON NAME. (MISXXX)
C  MTIMGE = NUMBER OF TAXA FOR WHICH TAXON IMAGES WERE SPECIFIED BY NAME
C    IN THE `TAXON IMAGES' DIRECTIVE.. (MISXXX)
C  MTO = THE WORD 'TO'. (EXICHA)
C  MWL = MAXIMUM WORD LENGTH. (JSTWD, JSTTPS)
C  NADNAM = NUMBER OF TAXA FOR WHICH TAXON IMAGES WERE SPECIFIED BY NAME
C    IN THE `ADD CHARACTERS' DIRECTIVE. (MISXXX)
C  NAFLG = BIT ARRAY TO FLAG INAPPLICABLE CHARACTERS.
C  NB = NUMBER AT BEGINNING.
C  NBITS = NUMBER OF BITS ACCESSIBLE FOR BIT MANIPULATION IN A WORD.
C    MUST BE AT LEAST 31. NOTE: THE STANDARD BIT-MANIPULATION ROUTINES
C    PROVIDED WORK BY MULTIPLICATION AND DIVISION, AND CANNOT ACCESS THE
C    SIGN BIT. (WRDSIZ)
C  NC = NUMBER OF CHARACTERS. (DIMXXX)
C  NCERR = CUMULATIVE ERROR COUNTER. (INPXXX)
C  NCERRS = SAVED VALUE OF NCERR. (RDITEM)
C  NCHRWD = NUMBER OF CHARACTERS IN A WORD. (WRDSIZ)
C  NCODES = NUMBER OF CODE WORDS. (CICOD)
C  NCON1, ... NCON5 = NUMBERS OF TYPE-1...5 CONTROL PHRASES.
C    (DIR1XX,...DIR5XX)
C  NDEC = NUMBERS OF DECIMAL PLACES FOR OUTPUT OF REAL CHARACTER VALUES.
C  NE = NUMBER AT END.
C  NEM(I) = REMAINING NUMBER OF ERROR MESSAGES THAT CAN BE OUTPUT ON
C    LOGICAL UNIT I BEFORE DATA LINE NEEDS TO BE RELISTED. (LISXXX)
C  NEMM = MAXIMUM NUMBER OF ERROR MESSAGES TO BE LISTED BEFORE DATA
C    LINE NEEDS TO BE RELISTED. (LISXXX)
C  NEMNAM = NUMBER OF TAXA FOR WHICH TAXON IMAGES WERE SPECIFIED BY NAME
C    IN THE `EMPHASIZE CHARACTERS' DIRECTIVE. (MISXXX)
C  NEWFL = ITEM NUMBERS AT WHICH A NEW OUTPUT FILE IS REQUIRED.
C    THE FIRST ELEMENT IS A POINTER THE NEXT ELEMENT TO BE USED,
C    THEN FOLLOW THE ITEMS NUMBERS, TERMINATED BY A 0 ELEMENT.
C  NEWFLS = WHETHER "NEW FILES AT ITEMS" DIRECTIVE IN EFFECT. (MISXXX)
C  NEWOR = NEW CHARACTER ORDER. NEWOR(JC) = OLD NUMBER OF NEW
C    CHARACTER JC.
C  NFONT = NUMBER OF OVERLAY FONTS ALLOWED. (FNTXXX)
C  NIERR = NUMBER OF ERRORS IN ITEM.
C  NINPUT = NUMBER OF INPUT FILES OPEN (CURRENTLY LIMITED TO 1) (INPFIL)
C  NLANG = THE NUMBER OF LANGUAGES DEFINED IN THE 'ALTERNATIVE LANGUAGES'
C    DIRECTIVE. (LANGXX)
C  NLGR = NUMBER OF LINES TO BE GROUPED ON PAGE. (BLKLIN)
C  NLBL = NUMBER OF BLANK LINES. (BLKLIN)
C  NODELO = WHETHER DELTA OUTPUT IS PERMITTED FROM INTKEY. (MISXXX)
C  NORNG = NORMAL RANGE FLAGS.
C  NR = NUMBER OF RANGES; OR RECORD NUMBER.
C  NS = NUMBER OF STATES.
C  NSV = NUMBER OF VALUES IN A SUBGROUP.
C  NSERR = CUMULATIVE SEQUENCE-ERROR COUNTER. (INPXXX)
C  NSIG = NUMBER OF SIGNIFICANT SYMBOLS IN CODE WORDS. (CICOD, CONPHR)
C  NSTAT = NUMBERS OF CHARACTER STATES (FOR NON-NUMERIC CHARACTERS) OR
C    WHETHER THE CHARACTER HAS UNITS (FOR NUMERIC CHARACTERS).
C  NSQDIG = NUMBER OF DECIMAL DIGITS IN SEQUENCE NUMBER. (JSTXXX)
C  NTCOD = NUMBER OF CHARACTER-TYPE CODES. (TCHXXX)
C  NTFILE = TOTAL NUMBER OF ITEM OUTPUT FILES. (MISXXX)
C  NTHEAD = TOTAL NUMBER OF ITEM HEADINGS. (MISXXX)
C  NTIMGE = TOTAL NUMBER OF TAXA FOR WHICH TAXON IMAGES WERE SPECIFIED (MISXXX).
C  NTRAN = NUMBER OF TRANSLATION OPTIONS. MUST AGREE WITH SECOND
C    DIMENSION OF KODTRA. (DIR4)
C  NU = NUMBER OF LOGICAL UNITS IN LUNXXX. SET IN PARAMETER STATEMENTS
C    IN MODULES INOU AND DIRA.
C  NUM = A NUMBER.
C  NUMST0 = WHETHER TO NUMBER CHARACTER STATES FROM ZERO. DEFAULT IS TO
C    BEGIN AT 1.
C  NUN = NUMBER OF LOGICAL UNITS (DIMENSION OF LUNUSE ETC.) (LUOXXX)
C  NUNC = NUMBER OF UNCODED OR UNKNOWN ATTRIBUTES. (NATTI)
C  NW = NUMBER OF WORD IN VOCABULARY. (JSTWD, JSTTPS)
C  NVWD = NUMBER OF WORDS IN VOCABULARY. (VLWXXX)
C  NWERR = CUMULATIVE WARNING ERROR COUNTER. (INPXXX)
C  NWSK = NUMBER OF WORDS SKIPPED. (SKDELW)
C  OUTDIR = NAME OF OUTPUT DIRECTORY. (DIRYXX)
C  PID = PROGRAM IDENTIFICATION. (PIDXXX)
C  PIDP = PROGRAM IDENTIFICATION (PARAMETER).
C  PSEQ = SEQUENCE NUMBER OUTPUT BY SUBR. INDENT. (JSTXXX)
C  RV = REAL STATE VALUE.
C  SCALF = SCALING FACTORS FOR REAL NUMERIC CHARACTERS.
C  SCRNAM = NAMES OF SCRATCH FILES. (SCRNMX)
C  SEQ = CURRENT RECORD SEQUENCE NUMBER. (INQXXX)
C  SEQINC = SEQUENCE INCREMENT FOR OUTPUT RECORDS. (JSTXXX)
C  TNAME = CHARACTER STRING HOLDING THE CURRENT TAXON NAME. (TNAMEX)
C  VAL(IC) = VALUE FOR CHARACTER IC.
C  VMAX = MAXIMUM VALUE.
C  VMIN = MINIMUM VALUE.
C  VWORD = LIST OF WORDS FOR USE IN DESCRIPTIONS, ETC. (VWDXXX)
C  W = REAL STORAGE POOL. (BLANK COMMON)
C  WTC = CHARACTER WEIGHTS. (INITIALIZED TO -1 IN SUBR. CHKDIR.)
C  WTI = ITEM WEIGHTS. (INITIALIZED TO -1 IN SUBR. CHKDIR.)
C  WW1C = REAL WORKING SPACE OF LENGTH NC. USES SAME STORAGE AS MM1C.
C  WW2C = REAL WORKING SPACE OF LENGTH NC. USES SAME STORAGE AS MM2C.
C  WW1I = REAL WORKING SPACE OF LENGTH MI. USES SAME STORAGE AS MM1I.
C  WW2I = REAL WORKING SPACE OF LENGTH MI. USES SAME STORAGE AS MM2I.
C  WW1S = REAL WORKING SPACE OF LENGTH MS. USES SAME STORAGE AS MM1S.
C  WW2S = REAL WORKING SPACE OF LENGTH MS. USES SAME STORAGE AS MM2S.
C
C
C  CHANGES REQUIRED.
C
C  NEW-STATE-ORDERS MAY ALTER ORDER OF 'AND' AND 'TO' GROUPS IN
C    ATTRIBUTES, RENDERING THEM INVALID.
C  REMOVE REQUIREMENT ON ORDER WITH 'AND'.
C  COUNT WARNINGS AND PRINT TOTAL AT END.
C  CHANGE ITEM-SUBHEADINGS AND CHARACTER-HEADINGS TO ACCEPT MULTILINE
C    HEADINGS, E.G., #20. FRUITS// WOULD PRODUCE EXTRA LINE AFTER
C    A HEADING, OR A NEW LINE AFTER A SUBHEADING.
C  * AT END OF LINE GIVES BUG 2. TREAT AS *SEC.
C  NDEC SHOULD BE SET ONLY FOR REAL NUMERIC CHARACTERS.
C  TO SPECIFY THAT UNITS OF NUMERICAL CHARACTER ARE NOT SEPARATED FROM
C    THE NUMBER, START UNITS WITH HYPHEN. E.G., VEINS/ GIVES 2 VEINS,
C    -MM/ GIVES 2MM, --NERVED/ GIVES 2-NERVED.
C  IN CHKBIN, WHEN CHARACTER TYPES ARE PRINTED IN ERROR MESSAGE,
C    EXTERNAL MNEMONIC CODES SHOULD BE PRINTED.
C  CICOD COULD BE IMPROVED BY SCANNING WORD FOR EXTRA DELIMITER.
C    E.G., 20,RN21,OM .
C  IN SBOUND, SHOULD CHECK SPECIFICATIONS IN LINE WITH DOCUMENTATION -
C    & FOR UM, - FOR OTHERS.
C  IN FINDST, CODE NEW OM STATES SEPARATELY - DON'T ALLOW SEMI-INFINITE
C    INTERVALS. IN IN AND RN, ASSUME SEMI-INFINITE INTERVAL ONLY IF
C    THE OTHER ENDPOINT IS NOT GIVEN.
C  IN ATTRIBUTES WITHOUT VALUES, CONSIDER ALLOWING COMMA (E.G., 5, ).
C  STORE DESCRIPTIONS OF MASKED-IN CHARACTERS ONLY.
 
 
C  REVISION HISTORY.
C  17-MAR-89. IMPLEMENT 'SORT CHARACTERS' DIRECTIVE.
C  14-MAR-89. REMOVE BINARY I/O.
C  28-FEB-89. 'SCALE CHARACTERS' DIRECTIVE IMPLEMENTED.
C  24-FEB-89. MAKE 'ADD CHARACTERS' AND 'ITALICIZE CHARACTERS'
C    CUMULATIVE.
C  30-JAN-89. ADD "SOMETIMES INAPPLICABLE" CODING TO INTKEY.
C    V ILLGEAL FOR NUMERICS. FOR MULTISTATES, V IS EXPANDED TO FULL
C    CODING.
C  19-DEC-88. NEW FORMAT FOR INTEGERS IN INTKEY.
C  25-NOV-88. ADD 'USE NORMAL VALUES' TO OUTPUT PARAMETERS.
C  1-NOV-88. MODIFY CAP AND IGNOR FOR EXTENDED CHARACTER SET.
C    IMPLEMENT 'ADD CHARACTERS' AND 'ITALICIZE CHARACTERS'.
C  14-OCT-88. REMOVE CHECK FOR INPUT ASCII CODES > 126.
C  20-SEP-88. RUN-TIME STORAGE ALLOCATION IN MS-DOS VERSION.
C  21/9/88. SETDEP - IF CONTROLLING CHARACTER VARIABLE, UNRECORDED
C    DEPENDENT CHARACTERS SHOULD BE CODED INTERNALLY AS U/-.
C  29/8/88. FIX BUG IN RDKOD. DOES NOT DISTINGUISH BETWEEN MINUS AND
C    NOT APPLICABLE.
C  20/7/88. "DIAGNOSTIC CHARACTERS" AND "ITALICIZE DIAGNOSTIC CHARACTERS"
C    DIRECTIVES IMPLEMENTED.
C  15/7/88. "REPLACE STATE CODES" DIRECTIVE IMPLEMENTED.
C  13/7/88. UPDATE SUBR. RDKOD.
C  7/4/88.  "REPLACE SEMICOLON BY COMMA" DIRECTIVE IMPLEMENTED.
C  24/3/88. ALLOWED RANGE FOR 'DATA BUFFER SIZE' CORRECTED.
C  18/2/88. EXTREME RANGES: INPUT AND OUTPUT.
C  2/2/88. MANDATORY CHARACTERS IN OUTPUT SPECIFICATIONS.
C    "PRINT UNCODED CHARACTERS" REPLACES "OMIT UNCODED CHARACTERS".
C  31/12/87. EXTREME RANGES. "OMIT OR FOR CHARACTERS" DIRECTIVE.
C  18/12/87. INTKEY FORMAT.
C  25/11/87. ERROR IN 'USE LAST VALUE CODED' CORRECTED.
C  22/10/87. 'MANDATORY CHARACTERS' ERROR MESSAGE MADE WARNING.
C  14/10/87. WARNING FOR MASKED-OUT ITEMS WHEN TRANLATING INTO
C    DELTA FORMAT.
C  7/9/87. IMPLEMENTATION OF 'MANDATORY CHARACTERS' DIRECTIVE.
C  18/8/87. (1) ENFORCE CODING OF CONTROLLING CHARACTERS IF DEPENDENT
C   CHARACTERS ARE CODED. (2) IF CONTROLLING CHARACTER IS INAPPLICABLE,
C    ALL CHARACTERS DEPENDENT ON ANY STATE ARE ALSO INAPPLICABLE.
C  13/8/87. IMPLEMENTATION OF 'APPLICABLE CHARACTERS' AND 'INAPPLICABLE
C   CHARACTERS' DIRECTIVES.
C  11/8/87. JSTOUT MODIFIED SO AS NOT TO BREAK WORDS LONGER THAN OUTPUT
C    WIDTH.
C  22/7/87. DEFAULT INTEGER SIZE CHANGED TO INTEGER*4 FOR ALL VERSIONS.
C    FORMAT OF DIST OUTPUT FILE CHANGED. MACHINE-DEPENDENT MODULES
C    TIDIED. HANDLING OF SCRATCH FILES TIDIED. 'KEY ITEMS FILE' AND
C    'KEY CHARACTERS FILE' DIRECTIVES REPLACED BY 'KEY OUTPUT FILE'.
C    CYBER AND UNIVAC VERSIONS WITHDRAWN.
C  1/5/86. MAJOR CHANGES IN THE HANDLING OF FILES AND LOGICAL
C  UNITS. DIRECTIVES ACCEPT FILENAMES RATHER THAN LOGICAL UNIT NUMBERS.
C  NUMEROUS OTHER SMALL CHANGES - SOME DIRECTIVES WITHDRAWN, OTHERS
C  REWORDED. THIRD EDITION OF "USER'S GUIDE TO THE DELTA SYSTEM"
C  DOCUMENTS THE NEW SYSTEM.
C  1/7/85. NEW KEY FORMAT. *KEY CHARACTER LIST. NAMED VARIANTS #+.
C  16/4/85. ALLOW CHARACTER RANGES WHEN CODING ATTRIBUTES.
C  29/3/85. IMPLEMENT TYPE CHARACTER FOR CONTROL PHRASES.
C  31/8/84. SET DEFAULT INPUT WIDTH TO 120.
C  10/8/84. IMPLEMENT PRINT SUMMARY DIRECTIVE.
C  11/7/84. IMPLEMENT DEPENDENT CHARACTERS DIRECTIVE.
C  21/6/84. INSERT EN DASH [X-] FOR RANGES WHEN TYPESETTING.
C  18/4/84. GENERALIZATION OF IMPLICIT VALUES DIRECTIVE. NEW
C  COMPLEMENTARY DIRECTIVE - INSERT IMPLICIT VALUES.
C  5/4/84.  N/A VALID FOR TEXT CHARACTERS.
C  27/3/84. ADD TYPE-4 DIRECTIVE - 'OMIT INAPPLICABLES'.
C  22/3/84. EXCLUDED CHARACTERS OMITTED WHEN TRANSLATING UNCODED
C  ATTRIBUTES.
C  15/3/84. TRANSLATE INTO PAYNE FORMAT IMPLEMENTED
C  15/3/84. TRANSLATE INTO PANKHURST FORMAT COMPLETED.
C  15/3/84. NO. OF STATE CARDS (KEY FORMAT) IS CORRECTLY CALCULATED.
C  14/2/84. UPDATE COMMON BLOCKS JSTXXX, LUNXXX, LUOXXX TO PROVIDE AN
C  INTERNAL SCRATCH UNIT
C  25/8/83. USE-LAST-ATTRIBUTE CHANGED TO ACCEPT-DUPLICATE-VALUES.
C  VALUE-CONSTRAINTS CHANGED TO ALLOWED-VALUES.
C  FULL STOP AFTER NAME REMOVED FROM TAXON-NAME OUTPUT.
C  29/6/83. FULL STOP AFTER NAME REMOVED FROM NATURAL LANGUAGE OUTPUT.
C  13/6/83. TRANSLATION OF KEY CHARACTERS ADDED.
C  12/6/83. TRANSLATE-INTO-EXIR-FORMAT OPTION ADDED.
C  12/6/83. WRITE-CONTROL-CARDS DIRECTIVE CHANGED TO
C  PUNCH-SPECIFICATIONS.
C  NEW-STATE-ORDERS DIRECTIVE ADDED.
C  9/6/83. LIST-CHARACTERS, LIST-ITEMS, AND USE-LAST-ATTRIBUTES
C  DIRECTIVES ADDED.
C  4/6/83. VALUE-CONSTRAINTS DIRECTIVE ADDED.
C  PRINT-CHARACTER-DESCRIPTIONS AND PRINT-ITEM-DESCRIPTIONS DIRECTIVES
C  CHANGED TO PRINT-CHARACTERS AND PRINT-ITEMS.
C  1/6/83. TYPE-6 DIRECTIVES INCLUDED IN TYPE 5.
C  CHARACTER-DESCRIPTIONS DIRECTIVE CHANGED TO CHARACTER-LIST.
C  SENTNC MODIFIED TO COPE WITH TYPESETTING MARKS CONTAINING < OR >.
C  17/5/83. ITEM-SUBHEADINGS AND CHARACTER-HEADINGS DIRECTIVES ADDED.
C  9/5/83. ITALICIZE-FEATURES DIRECTIVE ADDED.
C  REPLACE-ANGLE-BRACKETS AND OMIT-UNCODED-ATTRIBUTES DIRECTIVES ADDED.
C  4/5/83. LINK-ATTRIBUTES AND OMIT-CHARACTER-NUMBERS DIRECTIVES ADDED.
C  NATURAL-LANGUAGE OUTPUT OF 'V', 'U', AND '-' ALTERED.
C  PRINT-INAPPLICABLES DIRECTIVE WITHDRAWN.
C  STORAGE ALLOCATION ALTERED. (SEPARATE STORAGE FOR SOME ARRAYS
C  ALLOCATED ONLY IF THE CORRESPONDING DIRECTIVE IS SPECIFIED.)
C  27/4/83. CHARACTER TYPE 'TEXT' ADDED.
C  NEW-LISTING-PAGE AND NEW-PRINT-PAGE MODIFIED.
C  LIST-HEADING AND PRINT-HEADING DIRECTIVES ADDED.
C  'MULTBET' AND 'BM' FORMATS CHANGED TO 'DCR-TAXON' AND 'PANKHURST'.
C  LOGICAL-UNIT CHECKING SIMPLIFIED AND IMPROVED.
C  'PRINT' OUTPUT FOR TYPESETTING ON PRINT UNIT INSTEAD OF PUNCH UNIT.
C  19/4/83. SPECIAL-STORAGE CODE MOVED TO MACHINE-DEPENDENT GROUPS.
 
 
      COMMON /ADRXXX/ IITYPC,IIMC,IIMI,IWTC,IWTI,INSTAT,IKSTAT,
     * INEWOR,INDEC,IICDES,ILCDES,IITMAD,IWW1C,IWW2C,IWW1I,IWW2I,
     * IWW1S,IWW2S,IIDAT,IIDAM,IIDAV,IIPARA,IIEMPF,ILINKC,IICHHD,
     * IITSHD,IISBND,IIVCON,IICDEP,ILSTDE,INEWFL,IIMPL1,IIMPL2,
     * IIMPFL,IISUMM,IICPTW,IICPTB,IITPTR,ILNAME,IINTRL,IMANDC,IRBND,
     * INBND,IITXPT,INORNG,IIOMOR,IIFILS,IIREPS,IIADDT,IIADDC,IIEMPT,
     * IIEMPC,IMINC,IMAXC,INUMRN,INAFLG,ISCALF,IISRTS,IICNOT,IICNGP,
     * IITYMK,IIFMT,IIOMPD,IIOMLO,IICIMG,IICIGP,IITIMG,IITREC,IPCERR,
     * IABERR,IIOMFC,IIALTC,IIADNM,IIADDL,IIEMNM,IIEMPL,IIOUSP,IICSYN,
     * IILANG,IICSTR,IITHD,IITHREC,IICDNAM,IITFIL,IITFREC,IIXHD,IIXHREC,
     * IIFNT,IIUSECC,IIFOFSET,IITLNK,IILREC,IITLNK2,IINAUTOCC,IIOSUBJ,
     * ILAST
      COMMON /ALPXXX/ KA,KB,KC,KD,KE,KF,KG,KH,KI,KJ,KK,KL,KM,
     *                KN,KO,KP,KQ,KR,KS,KT,KU,KV,KW,KX,KY,KZ
      COMMON /BLKXXX/ KBLANK
      COMMON /BINXXX/ IENDRC,LENDRC,INSBLK
      COMMON /DELXXX/ KDPLUS,KDSTAR,KDNUM,KDSOL,KDLBRA,KDRBRA,
     * KDCOM,KDRANG,KDAMP,KDCOLN,KDSTOP,KDINF,KDLPAR,KDRPAR,KDBSLSH
      COMMON /DIRXXX/ LDIR
      COMMON /DIR1XX/ NCON1,JDIR1(5)
      COMMON /DIR2XX/ NCON2,JDIR2(1)
      COMMON /DIR3XX/ NCON3,JDIR3(1)
      COMMON /DIR4XX/ NCON4,JDIR4(97)
      COMMON /DIR5XX/ NCON5,JDIR5(4)
      COMMON /DIMXXX/ NC,MI,MS,LIDAT,LCSTR
      COMMON /EOFXXX/ IEOF
      COMMON /FFFXXX/ KFF
      COMMON /FNTXXX/ IOFONT,NFONT
      COMMON /HEDXXX/ LHEAD,IHEAD(200)
      COMMON /CAPXXX/ KCAPMK,IOMCAP
      COMMON /IGNXXX/ ICMD,IGNTYP
      COMMON /INIXXX/ JI,JT,JIM,IVARIT,MASTIN,MISTOP
      COMMON /INPFIL/ NINPUT
      COMMON /INPXXX/ IBUF(121),JBUF,JBDAT,JEDAT,IDERR,NCERR,NSERR,NWERR
      COMMON /INQXXX/ ISEQ,SEQ,LIBUF,MIREC,LISIND,LLUNI,JLIS,LISOUT(132)
      COMMON /ITSXXX/ ITSS
      COMMON /JSTXXX/ IOUT(132,5),LOUT,ICAP,
     * JIOUT(5),IENDWD(5),INDEN(5),LWIDTH(5),PSEQ,SEQINC,NSQDIG
      COMMON /LANGXX/ IUSELNG1,IUSELNG2,NLANG
      COMMON /LISXXX/ ILISTC,ILISTD,ILISTI,ILISTP,NEM(19),NEMM
      COMMON /LUFXXX/ FNAME(19),LFNAME(19)
        CHARACTER FNAME*80
      COMMON /LUNDAX/ LRECDA,IRECDA
      COMMON /LUNDXX/ LUND
      COMMON /LUNXXX/ LUNE,LUNL,LUNO,LUNP,LUNS1,LUNBO,LUNBI,LUNI,LUNDA,
     * LUNS2,LUNS3,LUNS4,LUNS5,LUNS6,LUNS7
      COMMON /LUOXXX/ NUN,LPAGE,LPRINT,LTOP,LPRDEF,LPUDEF,
     * LUNCOM(15),LUNPRE(15),LUNUSE(19),LUNREC(19),LUNPAG(19)
      COMMON /LUTXXX/ LUNTI,LUNTO
      COMMON /MISXXX/ IMPVAL,IPACH,IPCHN,IPUNC,IRAB,IKEYCH,ICMPRS,
     * ITUNC,ITINAP,ITIMPL,IUNVAR,LNKC,IDEPC,LICDEP,IPSUMM,ICHSEQ,
     * ITMSEQ,INSRVA,IFATT,ITINTR,ICMAND,IUNRNG,IOMTOR,NEWFLS,IRSEMI,
     * IOMSTC,IADDCH,IEMPCH,IVARUN,ISCALC,ICNOTE,ICIMGE,ITIMGE,MTIMGE,
     * NTIMGE,IOMNSC,IOMCMT,IOMLOW,IERRPC,IERRAB,ICHNSE,NUMST0,IUMEAN,
     * NADNAM,NEMNAM,NODELO,IOMUSP,ICKYIMG,ITKYIMG,ISUPIMG,ICTIMGE,
     * ICTNAME,IHTML,IRTF,MTHEAD,NTHEAD,ITMHDGS,LCDNAM,MTFILE,NTFILE,
     * ITMFILS,MXHEAD,NXHEAD,IDXHDGS,INSIMGFN,ICOFILE,IUCC,IOUNC,ITLINK,
     * MTLINK,NTLINK,NAUTOCC,IOUTSUBJ
      COMMON /NUMXXX/ KNUM(10),KDEC,KMINUS
      COMMON /DIRYXX/ OUTDIR,LOUTDIR,IMGDIR,LIMGDIR
        CHARACTER*80 OUTDIR,IMGDIR
      COMMON /PIDXXX/ PID
        CHARACTER*230 PID
      COMMON /REGXXX/ IREGHD(200),LREGHD,IREGSHD(200),LREGSHD,
     * IREGVD(20),LREGVD
      COMMON /SCRCXX/ LRECSC
      COMMON /SCRNMX/ SCRNAM(7)
        CHARACTER*8 SCRNAM
      COMMON /SCRXXX/ LUNTS1,LUNTS2,LUNTS3,LUNTS4,LUNTS5,LUNTS6,LUNTS7
      COMMON /SCR4XX/ LRECS4,IRECS4
      COMMON /SCR5XX/ LRECS5,IRECS5
      COMMON /SCR6XX/ LRECS6,IRECS6
      COMMON /SHOXXX/ LSHOW,ISHOW(200)
      COMMON /STOXXX/ ISTYPE,LRECSS
      COMMON /SYMXXX/ KPOINT,KDASH,KSTAR,KVERT,KEQUAL,KCOMMA,KSEMIC,
     * KCOLON,KSTOP,KSOL,KLPAR,KRPAR,KDOLLA,KQUEST,KEXCL,KAT,KLBRACE,
     * KRBRACE
      COMMON /TCHXXX/ NTCOD,ITCOD(2,7),JTCOD(7)
      COMMON /TNAMEX/ TNAME,LTNAME
        CHARACTER*256 TNAME
      COMMON /TPSXXX/ ITPSET,NTYPMK,IFBEGIN,IFEND
      COMMON /TRNXXX/ IPCHAR,IPITEM,IPNAME,ITRAN
      COMMON /UNUXXX/ ILUNU
      COMMON /VALXXX/ KVAR,KUNK,KNA,KVAL(64),LKVAL
      COMMON /VWDXXX/ VWORD(18)
        CHARACTER*40 VWORD
      COMMON /VLWXXX/ NVWD,MAXVWD,LVWD(18),IBPUNC,IEPUNC,
     * KVSTOP,KVCOM1,KVCOM2,KVSEMI,KVDEC
      COMMON /ULAXXX/ IULA
      COMMON /WRDSIZ/ NBITS,NCHRWD
      COMMON /WRKXXX/ IWRK(132)

      DIMENSION W(LW),IW(LW)
 
      CALL BLKDAT
      CALL INITIO
      CALL MEM (W, LW, IWST)
      CALL INITM (W(IWST), IW(IWST), LW)
 
C--   READ AND PROCESS DIRECTIVES.
  100 IDERR = 0
 
        CALL DIRA (IR, W(IWST), IW(IWST), LW)
        IF (IR.GE.2)  GO TO 8000
        IF (IR.NE.0)  GO TO 6000
C
        CALL DIR1 (IR, W(IWST), IW(IWST), LW)
        IF (IR.NE.0)  GO TO 6000
C
        CALL DIR2 (IR, W(IWST), IW(IWST), LW)
        IF (IR.NE.0)  GO TO 6000
C
        CALL DIR3 (IR, W(IWST), IW(IWST), LW)
        IF (IR.NE.0)  GO TO 6000
C
        CALL DIR4 (IR, W(IWST), IW(IWST), LW)
        IF (IR.NE.0)  GO TO 6000
C
        IR = 0
  510   CALL DIR5 (IR, W(IWST), IW(IWST), LW, IC, JCSTR)
          IF (IR.EQ.0)  GO TO 5000
          IF (IR.LT.0)  GO TO 6000
        GO TO 510
C
C       INVALID CONTROL PHRASE.
 5000   CALL MESSA (99, 1, 0)
        JBUF = JBUF + 1
        CALL SKDELW (0)
C
 6000   GO TO 100
C
C--   FINISH.
 8000 IF (ILISTD.NE.0)  CALL IPRT (2, -1)
      CALL EXTERM
      STOP
      END
